# Generated by Django 4.0.5 on 2022-06-05 15:41

from django.db import migrations, models
import django.db.models.deletion
import social_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('Impressions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name=social_django.models.UserSocialAuth),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth'),
        ),
    ]
