# Generated by Django 4.0.5 on 2022-06-05 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Impressions_app', '0003_alter_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_name', models.CharField(max_length=40)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('description', models.TextField(max_length=4000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
