# Generated by Django 4.0.5 on 2022-06-06 15:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Impressions_app', '0004_placemarker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemarker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placemarker',
            name='y_position',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-86), django.core.validators.MaxValueValidator(86)]),
        ),
    ]
